### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by elch10** [Naereen/Makefiles-support-for-VSCode#10]
After upgrading vscode to 1.21.0 this extension doesn't work anymore
![default](https://user-images.githubusercontent.com/15147137/37172738-b5cebdc0-2322-11e8-80a1-8bd8933aa0af.png)

**Comment by Naereen** [comment]
Hi, thanks for reporting this.

Actually, from your screenshot, I don't see the issue, the file is colored. It's just that my extension is very limited, and the syntax coloration is not perfect.

And since v1.21 VSCode has a builtin extension for Makefiles (see [this remark](https://github.com/Naereen/Makefiles-support-for-VSCode#makefiles-support-for-vscode), and [this folder](https://github.com/Microsoft/vscode/tree/master/extensions/make)), so it's probably better to uninstall mine.
I never had the time to finish it properly, I'm glad to see they did one on their own.
